apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "todo_db"
  DB_USER: "todo_user"
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
type: Opaque
stringData:
  DB_PASSWORD: "todo_pass"
  POSTGRES_PASSWORD: "todo_pass"
